In [3]:
import time
from IPython.display import clear_output
import numpy    as np
import pandas   as pd
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.pipeline import Pipeline ,make_pipeline
from sklearn import impute
from sklearn import compose
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score, balanced_accuracy_score, plot_confusion_matrix,roc_auc_score
from sklearn import set_config
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler,Normalizer,PowerTransformer,QuantileTransformer, RobustScaler,StandardScaler,LabelEncoder, OneHotEncoder,OrdinalEncoder
from sklearn.tree          import DecisionTreeClassifier
from sklearn.linear_model  import LogisticRegression    
from xgboost               import XGBClassifier
from lightgbm              import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import sklearn
set_config(display='diagram') # Useful for display the pipeline
print("Pandas  ", pd.__version__)
print("Sklearn ", sklearn.__version__) # Try to use 0.24



Pandas   1.2.4
Sklearn  0.24.2


In [6]:
data = pd.read_csv('./data/feature_eng.csv')
data.head(5)

id    user  android_sensor_gyroscope_mean  \
0  16170    Luca                       0.001651   
1  15871    Luca                       0.036326   
2  16811    Luca                       0.001525   
3  15831    Luca                       0.036440   
4    876  andrea                       0.183202   

   android_sensor_accelerometer_std  android_sensor_gyroscope_std  \
0                          0.014626                      0.000737   
1                          1.775944                      0.020290   
2                          0.011199                      0.000713   
3                          0.862553                      0.010553   
4                          0.504117                      0.098819   

   android_sensor_gyroscope_uncalibrated_mean  \
0                                    0.016221   
1                                    0.039023   
2                                    0.016302   
3                                    0.050759   
4                                    0.265652   

   android_sensor_accelerometer_max  android_sensor_linear_acceleration_mean  \
0                          9.849411                                 0.020978   
1                         17.146631                                 0.879220   
2                          9.849262                                 0.034110   
3                         12.304298                                 1.488361   
4                         10.891645                                 1.658308   

   speed_mean  android_sensor_rotation_vector_mean  \
0    0.180379                             0.050413   
1   14.679876                             0.999981   
2    0.180379                             0.610456   
3   14.679876                             0.998112   
4   14.679876                             0.322242   

   android_sensor_rotation_vector_max  android_sensor_accelerometer_min  \
0                            0.056351                          9.758895   
1                            0.999999                          7.707437   
2                            0.610456                          9.804817   
3                            0.998112                          7.659674   
4                            0.378193                          8.965621   

   android_sensor_magnetic_field_uncalibrated_min  sound_min target  acc_gyro  \
0                                       51.199707        NaN  Still  0.000083   
1                                       82.409890  89.065143    Car  0.036325   
2                                       55.501802        NaN  Still  0.000931   
3                                       95.664309  87.470377    Car  0.036372   
4                                      156.795909  89.770732    Car  0.059035   

   stillness  walk_sensor  workout_motion  
0  19.845629     9.793060        0.000083  
1  87.529351    16.146632        0.036325  
2  15.713616     9.238806        0.000931  
3  81.737122    11.306185        0.036372  
4   5.101411    10.513452        0.059035

In [22]:
data.describe()

id  android_sensor_gyroscope_mean  \
count   5893.000000                    5173.000000   
mean   10685.407263                       0.312536   
std     6921.229833                       0.554585   
min        0.000000                       0.000000   
25%     4502.000000                       0.015824   
50%    10959.000000                       0.053366   
75%    17049.000000                       0.256315   
max    22045.000000                       5.662153   

       android_sensor_accelerometer_std  android_sensor_gyroscope_std  \
count                       5893.000000                   5172.000000   
mean                           0.982987                      0.189903   
std                            1.505615                      0.342901   
min                            0.001286                      0.000000   
25%                            0.078055                      0.007552   
50%                            0.369163                      0.028408   
75%                            1.058376                      0.177164   
max                           12.879851                      4.980892   

       android_sensor_gyroscope_uncalibrated_mean  \
count                                 5094.000000   
mean                                     0.312807   
std                                      0.537925   
min                                      0.001157   
25%                                      0.038873   
50%                                      0.060895   
75%                                      0.256838   
max                                      3.863194   

       android_sensor_accelerometer_max  \
count                       5893.000000   
mean                          12.247691   
std                            5.178436   
min                            8.801019   
25%                           10.015566   
50%                           10.602081   
75%                           12.291575   
max                           66.886376   

       android_sensor_linear_acceleration_mean   speed_mean  \
count                              5399.000000  5893.000000   
mean                                  1.315971    11.219236   
std                                   2.065444    12.827053   
min                                   0.000825     0.180379   
25%                                   0.101898     1.120206   
50%                                   0.471370     5.368554   
75%                                   1.388990    14.679876   
max                                  23.110842    34.722137   

       android_sensor_rotation_vector_mean  \
count                          5172.000000   
mean                              0.765932   
std                               0.263393   
min                               0.020350   
25%                               0.651735   
50%                               0.880361   
75%                               0.972333   
max                               1.000000   

       android_sensor_rotation_vector_max  android_sensor_accelerometer_min  \
count                         5172.000000                       5893.000000   
mean                             0.779000                          8.426262   
std                              0.262881                          1.783007   
min                              0.031072                          0.337166   
25%                              0.666105                          7.805295   
50%                              0.904736                          9.123124   
75%                              0.982342                          9.691731   
max                              1.000000                         12.115013   

       android_sensor_magnetic_field_uncalibrated_min    sound_min  \
count                                     5094.000000  4899.000000   
mean                                       136.955896    78.451658   
std                                         70.764992    14.262912   
min                            

# Create test data 

In [7]:
# create test data from some user 
df=data.copy()
user1=df[df['user']=='Pierpaolo']
user2=df[df['user']=='IvanHeibi']
user3=df[df['user']=='AndreaCarpineti']
user4=df[df['user']=='Elena']
users=[user1,user2,user3,user4]
df_test=pd.concat(users)
df_test.head(5)

id       user  android_sensor_gyroscope_mean  \
33   19919  Pierpaolo                       0.615399   
54   19494  Pierpaolo                       0.447802   
102  20104  Pierpaolo                       0.069503   
121  19436  Pierpaolo                       0.045041   
172  20245  Pierpaolo                       1.734294   

     android_sensor_accelerometer_std  android_sensor_gyroscope_std  \
33                           1.283204                      0.655962   
54                           0.361961                      0.116564   
102                          0.070605                      0.048140   
121                          0.451773                      0.027367   
172                          4.272022                      1.400249   

     android_sensor_gyroscope_uncalibrated_mean  \
33                                     0.778458   
54                                     0.334574   
102                                    0.078626   
121                                    0.038644   
172                                    1.331566   

     android_sensor_accelerometer_max  \
33                          14.028126   
54                           9.963264   
102                          9.187340   
121                          9.563967   
172                         17.743662   

     android_sensor_linear_acceleration_mean  speed_mean  \
33                                  1.721314    1.120206   
54                                  0.958200    5.368554   
102                                 0.868719    1.120206   
121                                 0.958079    5.368554   
172                                 8.823918    1.120206   

     android_sensor_rotation_vector_mean  android_sensor_rotation_vector_max  \
33                              0.955202                            0.955202   
54                              0.983561                            0.989576   
102                             0.787570                            0.802811   
121                             0.993876                            0.996117   
172                             0.985658                            0.993053   

     android_sensor_accelerometer_min  \
33                           9.764513   
54                           8.712177   
102                          9.012243   
121                          8.246220   
172                          3.332163   

     android_sensor_magnetic_field_uncalibrated_min  sound_min   target  \
33                                        36.378866  77.064227  Walking   
54                                        77.496043  74.178611      Bus   
102                                       91.951478   6.020600  Walking   
121                                       70.436446  72.559600      Bus   
172                                       90.118737  73.702289  Walking   

     acc_gyro  stillness  walk_sensor  workout_motion  
33   0.587830   1.956216    13.072924        0.587830  
54   0.440440   3.105259     8.973688        0.440440  
102  0.054738   1.466640     8.384529        0.054738  
121  0.044765  16.507783     8.567851        0.044765  
172  1.709421   3.050902    16.750609        1.709421

## Subtract test data from data 

In [8]:
df_train = df.merge(df_test, how='left', indicator=True)
df_train = df_train[df_train['_merge'] == 'left_only']
df_train=df_train.drop('_merge',axis=1)
df_train.head(5)

id    user  android_sensor_gyroscope_mean  \
0  16170    Luca                       0.001651   
1  15871    Luca                       0.036326   
2  16811    Luca                       0.001525   
3  15831    Luca                       0.036440   
4    876  andrea                       0.183202   

   android_sensor_accelerometer_std  android_sensor_gyroscope_std  \
0                          0.014626                      0.000737   
1                          1.775944                      0.020290   
2                          0.011199                      0.000713   
3                          0.862553                      0.010553   
4                          0.504117                      0.098819   

   android_sensor_gyroscope_uncalibrated_mean  \
0                                    0.016221   
1                                    0.039023   
2                                    0.016302   
3                                    0.050759   
4                                    0.265652   

   android_sensor_accelerometer_max  android_sensor_linear_acceleration_mean  \
0                          9.849411                                 0.020978   
1                         17.146631                                 0.879220   
2                          9.849262                                 0.034110   
3                         12.304298                                 1.488361   
4                         10.891645                                 1.658308   

   speed_mean  android_sensor_rotation_vector_mean  \
0    0.180379                             0.050413   
1   14.679876                             0.999981   
2    0.180379                             0.610456   
3   14.679876                             0.998112   
4   14.679876                             0.322242   

   android_sensor_rotation_vector_max  android_sensor_accelerometer_min  \
0                            0.056351                          9.758895   
1                            0.999999                          7.707437   
2                            0.610456                          9.804817   
3                            0.998112                          7.659674   
4                            0.378193                          8.965621   

   android_sensor_magnetic_field_uncalibrated_min  sound_min target  acc_gyro  \
0                                       51.199707        NaN  Still  0.000083   
1                                       82.409890  89.065143    Car  0.036325   
2                                       55.501802        NaN  Still  0.000931   
3                                       95.664309  87.470377    Car  0.036372   
4                                      156.795909  89.770732    Car  0.059035   

   stillness  walk_sensor  workout_motion  
0  19.845629     9.793060        0.000083  
1  87.529351    16.146632        0.036325  
2  15.713616     9.238806        0.000931  
3  81.737122    11.306185        0.036372  
4   5.101411    10.513452        0.059035

In [9]:
print(df_train.shape)
print(df_test.shape)

(4985, 19)
(908, 19)


## drop id ,time, user columns

In [10]:
unimp    = ['id','user']
df_train = df_train.drop(unimp,axis=1)
df_test  = df_test.drop(unimp,axis=1)

In [11]:
df_train=df_train.drop('speed_mean',axis=1)
df_test=df_test.drop('speed_mean',axis=1)

In [12]:
print(df_train.shape)
print(df_test.shape)

(4985, 16)
(908, 16)


In [13]:
X=df_train.drop('target',axis=1)
y=df_train.target
X_test=df_test.drop('target',axis=1)
y_test=df_test.target

# Pipeline 

In [17]:
num_attribs=df_train.drop('target',axis=1).columns.to_list()
num_pip=Pipeline([('imputer',impute.SimpleImputer(strategy='median')),
                  ('scalar',MinMaxScaler()),
               ])  # ('PCA',PCA(n_components=12))
preprocessor=compose.ColumnTransformer([
    ('num',num_pip,num_attribs)
])

In [18]:
# pipeline for model
classifier_models = {
"DecisionTreeClassifier": DecisionTreeClassifier(),
'KNeighborsClassifier':KNeighborsClassifier(6),
'LogisticRegression':LogisticRegression(),
"RandomForestClassifier":RandomForestClassifier(),
"GradientBoostingClassifier":GradientBoostingClassifier(),
"XGBClassifier":XGBClassifier(),
"LGBMClassifier":LGBMClassifier(),
'GaussianNB':GaussianNB(),

}
# make pipline with  preprocessing 
classifier_models = {name: make_pipeline(preprocessor, model) for name, model in classifier_models.items()}
classifier_models["GradientBoostingClassifier"]

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scalar',
                                                                   MinMaxScaler())]),
                                                  ['android_sensor_gyroscope_mean',
                                                   'android_sensor_accelerometer_std',
                                                   'android_sensor_gyroscope_std',
                                                   'android_sensor_gyroscope_uncalibrated_mean',
                                                   'android_sensor_accelerometer_max',
                                                   'android_sensor_linear_acceleration_mean',
                                                   'android_sensor_rotation_vector_mean',
                                                   'android_sensor_rotation_vector_max',
                                                   'android_sensor_accelerometer_min',
                                                   'android_sensor_magnetic_field_uncalibrated_min',
                                                   'sound_min', 'acc_gyro',
                                                   'stillness', 'walk_sensor',
                                                   'workout_motion'])])),
                ('gradientboostingclassifier', GradientBoostingClassifier())])

In [19]:


x_train, x_val, y_train, y_val = train_test_split(X, y,test_size=0.4,stratify = y,random_state=10 )
results = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [],'Time': []})
for model_name, model in classifier_models.items():
    start_time = time.time()
    model.fit(x_train, y_train)
    total_time = time.time() - start_time
    valid_pred = model.predict(x_val)
    results = results.append({"Model":    model_name,
                              "Accuracy": accuracy_score(y_val, valid_pred)*100,
                              "Bal Acc.": balanced_accuracy_score(y_val, valid_pred)*100,
                    
                              "Time":     total_time},
                              ignore_index=True)
results_ord = results.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
results_ord.index += 1 
results_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='#5fba7d')


ValueError: Input contains infinity or a value too large for dtype('float64').

# Best model for test data  

In [20]:
best_model=LGBMClassifier()
name='LGBMClassifier'

In [21]:
clf=Pipeline([('preprocess',preprocessor),('classification',best_model)])
test_result = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [],'Time': []})
start_time = time.time()
clf.fit(X, y)
total_time = time.time() - start_time
pred = clf.predict(X_test)
test_result = test_result.append({"Model":    name,
                          "Accuracy": accuracy_score(y_test, pred)*100,
                          "Bal Acc.": balanced_accuracy_score(y_test, pred)*100,
                          "Time":     total_time},
                          ignore_index=True)
test_result_ord = test_result.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
test_result_ord.index += 1 
test_result_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='#5fba7d')



ValueError: Input contains infinity or a value too large for dtype('float64').

In [23]:
print(classification_report(y_test, pred))
print()
print(confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

         Bus       0.73      0.92      0.81       164
         Car       0.44      1.00      0.61        34
       Still       0.65      0.99      0.79        76
       Train       1.00      0.99      0.99        86
     Walking       0.99      0.76      0.86       548

    accuracy                           0.84       908
   macro avg       0.76      0.93      0.81       908
weighted avg       0.89      0.84      0.85       908


[[151   8   0   0   5]
 [  0  34   0   0   0]
 [  0   0  75   0   1]
 [  0   1   0  85   0]
 [ 57  35  40   0 416]]


# with optuna paramater

In [49]:

m_=LGBMClassifier()
model_m=Pipeline([('preprocess',preprocessor),('classification',m_)])

In [50]:
model_m.fit(X,y)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scalar',
                                                                   MinMaxScaler())]),
                                                  ['android_sensor_gyroscope_mean',
                                                   'android_sensor_accelerometer_std',
                                                   'android_sensor_gyroscope_std',
                                                   'android_sensor_gyroscope_uncalibrated_mean',
                                                   'android_sensor_accelerometer_max',
                                                   'android_sensor_linear_acceleration_mean',
                                                   'android_sensor_rotation_vector_mean',
                                                   'android_sensor_rotation_vector_max',
                                                   'android_sensor_accelerometer_min',
                                                   'android_sensor_magnetic_field_uncalibrated_min',
                                                   'sound_min', 'acc_gyro',
                                                   'Lin_speed'])])),
                ('classification', LGBMClassifier())])

In [51]:
pred_=model_.predict(X_test)
print(f"Accuracy {accuracy_score(y_test, pred_)*100}")
print(classification_report(y_test, pred_))
print()
print(confusion_matrix(y_test, pred_))

Accuracy 83.81057268722468
              precision    recall  f1-score   support

         Bus       0.73      0.92      0.81       164
         Car       0.44      1.00      0.61        34
       Still       0.65      0.99      0.79        76
       Train       1.00      0.99      0.99        86
     Walking       0.99      0.76      0.86       548

    accuracy                           0.84       908
   macro avg       0.76      0.93      0.81       908
weighted avg       0.89      0.84      0.85       908


[[151   8   0   0   5]
 [  0  34   0   0   0]
 [  0   0  75   0   1]
 [  0   1   0  85   0]
 [ 57  35  40   0 416]]


#  Drop some feature from target  beacuse of confusion materix result 

## Drop car  category 

In [52]:
df_test_1   =df_test[df_test['target']!='Car']
df_train_1  =df_train[df_train['target']!='Car']

In [53]:
print(df_test.shape)
print(df_train.shape)

(908, 14)
(4985, 14)


# How much info reduced 

In [54]:
print(f" After drop Car category we  reduce \n test data {100-df_test_1.shape[0]/df_test.shape[0]*100} % \n train data {100-df_train_1.shape[0]/df_train.shape[0]*100} %")

 After drop Car category we  reduce 
 test data 3.7444933920704813 % 
 train data 22.988966900702096 %


In [55]:
print(df_train_1.shape)
print(df_test_1.shape)

(3839, 14)
(874, 14)


In [56]:
X_=df_train_1.drop('target',axis=1)
y_=df_train_1.target
X_test_=df_test_1.drop('target',axis=1)
y_test_=df_test_1.target

# train data 

In [57]:
x_train_, x_val_, y_train_, y_val_ = train_test_split(X_, y_,test_size=0.4,stratify = y_,random_state=10 )
result_new = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [],'Time': []})
for model_name, model in classifier_models.items():
    start_time_ = time.time()
    model.fit(x_train_, y_train_)
    total_time_= time.time() - start_time_
    valid_pred_new = model.predict(x_val_)
    result_new = result_new.append({"Model":    model_name,
                              "Accuracy": accuracy_score(y_val_, valid_pred_new)*100,
                              "Bal Acc.": balanced_accuracy_score(y_val_, valid_pred_new)*100,
                              "Time":     total_time_},
                              ignore_index=True)
result_new_ord = result_new.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
result_new_ord.index += 1 
result_new_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='#5fba7d')

[19:02:30] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


#  The highest accuracy model selected  manual tuning 

In [43]:

best_=LGBMClassifier(boosting_type='gbdt', num_leaves=60, max_depth=6, learning_rate=0.07,
                          n_estimators=300, subsample_for_bin=200000, objective=None, class_weight=None,
                          min_split_gain=0.0, min_child_weight=0.001, min_child_samples=20, subsample=1.0, 
                          subsample_freq=0, colsample_bytree=1.0, reg_alpha=0.0, reg_lambda=0.0, 
                          random_state=None, n_jobs=- 1, silent=True, importance_type='split')
model_=Pipeline([('preprocess',preprocessor),('classification',best_)])

In [58]:
model_.fit(X_,y_)
pred_test_1=model_.predict(X_test_)

In [45]:
accuracy_score(y_test_, pred_test_1)*100,

(89.58810068649885,)

In [46]:
print(classification_report(y_test_, pred_test_1))
print()
print(confusion_matrix(y_test_, pred_test_1))

              precision    recall  f1-score   support

         Bus       0.78      0.96      0.86       164
       Still       0.65      0.99      0.78        76
       Train       1.00      1.00      1.00        86
     Walking       0.99      0.85      0.91       548

    accuracy                           0.90       874
   macro avg       0.85      0.95      0.89       874
weighted avg       0.92      0.90      0.90       874


[[158   1   0   5]
 [  0  75   0   1]
 [  0   0  86   0]
 [ 44  40   0 464]]


# Optuna find best parameter for selected model

In [47]:
from sklearn.calibration import CalibratedClassifierCV
import optuna

In [48]:
oth=Pipeline([('preprocess',preprocessor),('classification',GaussianNB())])

In [ ]:
 n_estimators = trial.suggest_int('n_estimators', 2, 20)
max_depth = int(trial.suggest_loguniform('max_depth', 1, 32))

In [296]:
import optuna

def objective(trial):

    boosting_type = trial.suggest_categorical("boosting_type", ["gbdt", "rf"])
    max_depth = trial.suggest_int('max_depth', 1, 32)
    n_estimators = trial.suggest_int("n_estimators", 100,500)
    learning_rate=trial.suggest_float("learning_rate", 0.001,0.1)
    min_data_in_leaf= trial.suggest_int("min_data_in_leaf", 10,500)
    
    lg_lgbm = LGBMClassifier( boosting_type=boosting_type, max_depth=max_depth, 
            n_estimators=n_estimators,learning_rate=learning_rate,min_data_in_leaf=min_data_in_leaf
        )

    score = cross_val_score(lg_lgbm, X_,y_, n_jobs=-1, cv=3)
    accuracy = score.mean()
    return accuracy

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

trial = study.best_trial
print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))


[I 2021-05-19 17:30:08,714] A new study created in memory with name: no-name-8310e34b-583d-4b71-b7c7-14c5a34bb47d
[W 2021-05-19 17:30:08,787] Trial 0 failed, because the objective function returned nan.
[I 2021-05-19 17:30:09,823] Trial 1 finished with value: 0.978119095321866 and parameters: {'boosting_type': 'gbdt', 'max_depth': 11, 'n_estimators': 107, 'learning_rate': 0.03497645397932077, 'min_data_in_leaf': 153}. Best is trial 1 with value: 0.978119095321866.
[I 2021-05-19 17:30:10,759] Trial 2 finished with value: 0.9627492181391712 and parameters: {'boosting_type': 'gbdt', 'max_depth': 14, 'n_estimators': 239, 'learning_rate': 0.018242798350919038, 'min_data_in_leaf': 456}. Best is trial 1 with value: 0.978119095321866.
[W 2021-05-19 17:30:10,816] Trial 3 failed, because the objective function returned nan.
[I 2021-05-19 17:30:12,441] Trial 4 finished with value: 0.974731642559291 and parameters: {'boosting_type': 'gbdt', 'max_depth': 27, 'n_estimators': 255, 'learning_rate': 0.

[W 2021-05-19 17:30:29,073] Trial 62 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,149] Trial 63 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,204] Trial 64 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,260] Trial 65 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,319] Trial 66 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,376] Trial 67 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,434] Trial 68 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,488] Trial 69 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,545] Trial 70 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,605] Trial 71 failed, because the objective function returned nan.
[W 2021-05-19 17:30:29,666] Trial 72 failed, because the objective function returned nan.
[W 2021-05

Accuracy: 0.9843713350273652
Best hyperparameters: {'boosting_type': 'gbdt', 'max_depth': 29, 'n_estimators': 408, 'learning_rate': 0.03658524797730336, 'min_data_in_leaf': 198}


# With optuna best parameter

 the best accuracy  **91.18993135011442**  in max_depth= 5, n_estimators= 300, num_leaves=70,min_data_in_leaf=60,learning_rate= 0.069

In [317]:

lgb_af_=LGBMClassifier( max_depth= 5
, n_estimators= 300, num_leaves=70,min_data_in_leaf=60,learning_rate= 0.069)
model_end=Pipeline([('preprocess',preprocessor),('classification',lgb_af_)])

In [318]:
model_end.fit(X_,y_)
pred_test_end=model_end.predict(X_test_)

[LightGBM] [Warning] min_data_in_leaf is set=60, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=60


In [319]:
print(f"Accuracy {accuracy_score(y_test_, pred_test_end)*100}")
print(classification_report(y_test_, pred_test_end))
print()
print(confusion_matrix(y_test_, pred_test_end))

Accuracy 91.18993135011442
              precision    recall  f1-score   support

         Bus       0.83      0.95      0.89       164
       Still       0.67      0.99      0.80        76
       Train       0.98      1.00      0.99        86
     Walking       0.99      0.88      0.93       548

    accuracy                           0.91       874
   macro avg       0.87      0.95      0.90       874
weighted avg       0.93      0.91      0.92       874


[[156   0   2   6]
 [  0  75   0   1]
 [  0   0  86   0]
 [ 31  37   0 480]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3e7089f3-11a5-48ad-89c4-39a166311a14' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>