In [1]:
import time
from IPython.display import clear_output
import numpy    as np
import pandas   as pd
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.pipeline import Pipeline ,make_pipeline
from sklearn import impute
from sklearn import compose
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score, balanced_accuracy_score, plot_confusion_matrix,roc_auc_score
from sklearn import set_config
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import MinMaxScaler,Normalizer,PowerTransformer,QuantileTransformer, RobustScaler,StandardScaler,LabelEncoder, OneHotEncoder,OrdinalEncoder
from sklearn.tree          import DecisionTreeClassifier
from sklearn.linear_model  import LogisticRegression    
from xgboost               import XGBClassifier
from lightgbm              import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import sklearn
set_config(display='diagram') # Useful for display the pipeline
print("Pandas  ", pd.__version__)
print("Sklearn ", sklearn.__version__) # Try to use 0.24



Pandas   1.2.4
Sklearn  0.24.2


In [71]:
data = pd.read_csv('./data/data_5secondWindow .csv')
data.head(5)

id   time  activityrecognition#0  activityrecognition#1  \
0  16170   78.0                    NaN                  100.0   
1  15871  145.0                    NaN                  100.0   
2  16811  150.0                    NaN                  100.0   
3  15831  105.0                    NaN                   77.0   
4    876   77.0                    NaN                  100.0   

   android.sensor.accelerometer#mean  android.sensor.accelerometer#min  \
0                           9.811476                          9.758895   
1                           9.939207                          7.707437   
2                           9.827178                          9.804817   
3                           9.673039                          7.659674   
4                           9.993466                          8.965621   

   android.sensor.accelerometer#max  android.sensor.accelerometer#std  \
0                          9.849411                          0.014626   
1                         17.146631                          1.775944   
2                          9.849262                          0.011199   
3                         12.304298                          0.862553   
4                         10.891645                          0.504117   

   android.sensor.game_rotation_vector#mean  \
0                                  0.029340   
1                                  0.999925   
2                                  0.665215   
3                                  0.996221   
4                                  0.563792   

   android.sensor.game_rotation_vector#min  ...  sound#mean  sound#min  \
0                                 0.029014  ...         NaN        NaN   
1                                 0.999903  ...   89.200210  89.065143   
2                                 0.665213  ...         NaN        NaN   
3                                 0.993781  ...   87.470377  87.470377   
4                                 0.521799  ...   89.770732  89.770732   

   sound#max  sound#std  speed#mean  speed#min  speed#max  speed#std  target  \
0        NaN        NaN    0.000000   0.000000   0.000000   0.000000   Still   
1  89.335277   0.191013   16.539349  16.539349  16.539349   0.628595     Car   
2        NaN        NaN    0.000000   0.000000   0.000000   0.000000   Still   
3  87.470377   2.284186   17.739895  17.739895  17.739895   0.628595     Car   
4  89.770732   0.006389    9.000000   9.000000   9.000000        NaN     Car   

     user  
0    Luca  
1    Luca  
2    Luca  
3    Luca  
4  andrea  

[5 rows x 70 columns]

In [72]:
data.describe()

id         time  activityrecognition#0  \
count   5893.000000  5893.000000                    0.0   
mean   10685.407263   117.731716                    NaN   
std     6921.229833   126.474151                    NaN   
min        0.000000     3.000000                    NaN   
25%     4502.000000    31.000000                    NaN   
50%    10959.000000    70.000000                    NaN   
75%    17049.000000   152.000000                    NaN   
max    22045.000000   682.000000                    NaN   

       activityrecognition#1  android.sensor.accelerometer#mean  \
count            5893.000000                        5893.000000   
mean               87.718310                          10.007976   
std                24.562728                           0.655949   
min                 3.000000                           7.369055   
25%                90.000000                           9.737143   
50%               100.000000                           9.850143   
75%               100.000000                          10.078998   
max               100.000000                          17.427391   

       android.sensor.accelerometer#min  android.sensor.accelerometer#max  \
count                       5893.000000                       5893.000000   
mean                           8.426262                         12.247691   
std                            1.783007                          5.178436   
min                            0.337166                          8.801019   
25%                            7.805295                         10.015566   
50%                            9.123124                         10.602081   
75%                            9.691731                         12.291575   
max                           12.115013                         66.886376   

       android.sensor.accelerometer#std  \
count                       5893.000000   
mean                           0.982987   
std                            1.505615   
min                            0.001286   
25%                            0.078055   
50%                            0.369163   
75%                            1.058376   
max                           12.879851   

       android.sensor.game_rotation_vector#mean  \
count                               5094.000000   
mean                                   0.759280   
std                                    0.251174   
min                                    0.007770   
25%                                    0.640486   
50%                                    0.840643   
75%                                    0.963207   
max                                    1.000000   

       android.sensor.game_rotation_vector#min  ...  \
count                              5094.000000  ...   
mean                                  0.743872  ...   
std                                   0.255232  ...   
min                                   0.007616  ...   
25%                                   0.612155  ...   
50%                                   0.818037  ...   
75%                                   0.960858  ...   
max                                   1.000000  ...   

       android.sensor.step_counter#max  android.sensor.step_counter#std  \
count                      1487.000000                       232.000000   
mean                      10112.769334                         2.959475   
std                       11067.568076                         1.365350   
min                          28.000000                         1.414214   
25%                        1767.000000                         1.414214   
50%                        6096.000000                         3.027650   
75%                       12995.000000                         3.593976   
max                       33355.000000                         6.363961   

        sound#mean    sound#min    sound#max    sound#std   speed#mean  \
count  4899.000000  4899.000000  4899.000000  4062.000000  3520.000000   
mean     78.724855 

In [91]:
from random import shuffle

# Create test data 

In [115]:
# create test data from some user 
def split_data(df):
   
    # create random list of indices
    l = df.user.unique().tolist()
    shuffle(l)
    train_user=l[2:]
    test_user=l[:2]
    # get splitting indicies
    train=data[data['user'].isin(train_user)]
    test = data[data['user'].isin(test_user)]
    return train, test


In [116]:
df_train,df_test=split_data(data)

## Subtract test data from data 

In [117]:
df_train

id   time  activityrecognition#0  activityrecognition#1  \
0     16170   78.0                    NaN                  100.0   
1     15871  145.0                    NaN                  100.0   
2     16811  150.0                    NaN                  100.0   
3     15831  105.0                    NaN                   77.0   
4       876   77.0                    NaN                  100.0   
...     ...    ...                    ...                    ...   
5888  14125    4.0                    NaN                  100.0   
5889  19582   32.0                    NaN                   10.0   
5890  16178   86.0                    NaN                  100.0   
5891  10973  199.0                    NaN                  100.0   
5892   8278   55.0                    NaN                  100.0   

      android.sensor.accelerometer#mean  android.sensor.accelerometer#min  \
0                              9.811476                          9.758895   
1                              9.939207                          7.707437   
2                              9.827178                          9.804817   
3                              9.673039                          7.659674   
4                              9.993466                          8.965621   
...                                 ...                               ...   
5888                          10.066610                          4.564648   
5889                           9.964271                          8.768007   
5890                           9.812893                          9.772881   
5891                           9.831144                          9.807347   
5892                          11.051009                          5.203285   

      android.sensor.accelerometer#max  android.sensor.accelerometer#std  \
0                             9.849411                          0.014626   
1                            17.146631                          1.775944   
2                             9.849262                          0.011199   
3                            12.304298                          0.862553   
4                            10.891645                          0.504117   
...                                ...                               ...   
5888                         13.414389                          3.373972   
5889                         11.454213                          0.665529   
5890                          9.862587                          0.017633   
5891                          9.874450                          0.013485   
5892                         19.921068                          4.745098   

      android.sensor.game_rotation_vector#mean  \
0                                     0.029340   
1                                     0.999925   
2                                     0.665215   
3                                     0.996221   
4                                     0.563792   
...                                        ...   
5888                                  0.986319   
5889                                  0.648602   
5890                                  0.024392   
5891                                  0.481212   
5892                                  0.919815   

      android.sensor.game_rotation_vector#min  ...  sound#mean  sound#min  \
0                                    0.029014  ...         NaN        NaN   
1                                    0.999903  ...   89.200210  89.065143   
2                                    0.665213  ...         NaN        NaN   
3                                    0.993781  ...   87.470377  87.470377   
4                                    0.521799  ...   89.770732  89.770732   
...                                       ...  ...         ...        ...   
5888                                 0.974523  ...         NaN        NaN   
5889                                 0.648343  ...         NaN        NaN   
5890                                 0.024081  ...         N

In [103]:
print(df_train.shape)
print(df_test.shape)

(5447, 70)
(446, 70)


## drop id ,time, user columns

In [118]:
unimp    = ['id','user','time']
df_train = df_train.drop(unimp,axis=1)
df_test  = df_test.drop(unimp,axis=1)

In [ ]:
# df_train=df_train.drop('speed_mean',axis=1)
# df_test=df_test.drop('speed_mean',axis=1)

In [119]:
print(df_train.shape)
print(df_test.shape)

(5709, 67)
(184, 67)


In [106]:
def fill_nan_with_mean_training(training, test):
    trainingFill = training.copy()
    testFill = test.copy()
    trainingFill = trainingFill.fillna(trainingFill.mean())
    trainingFill = trainingFill.fillna(0)
    testFill = testFill.fillna(trainingFill.mean())
    testFill = testFill.fillna(0)
    return trainingFill, testFill

def scale_features(train, test):
    # build scaler to apply on training and test the same transformation
    scaler = StandardScaler().fit(train)
    train_features_scaled = scaler.transform(train)
    test_features_scaled = scaler.transform(test)
    return train_features_scaled, test_features_scaled

In [120]:
df_train_fill,df_test_fill=fill_nan_with_mean_training(df_train,df_test)

In [126]:
X=df_train_fill.drop('target',axis=1)
y=df_train_fill.target
X_test=df_test_fill.drop('target',axis=1)
y_test=df_test_fill.target

In [127]:
X_sc,X_test_sc=scale_features(X, X_test)

# Pipeline 

In [ ]:
# num_attribs=df_train.drop('target',axis=1).columns.to_list()
# num_pip=Pipeline([('imputer',impute.SimpleImputer(strategy='median')),
#                   ('scalar',MinMaxScaler()),
#                ])  # ('PCA',PCA(n_components=12))
# preprocessor=compose.ColumnTransformer([
#     ('num',num_pip,num_attribs)
# ])

In [128]:
# pipeline for model
classifier_models = {
"DecisionTreeClassifier": DecisionTreeClassifier(),
'KNeighborsClassifier':KNeighborsClassifier(6),
'LogisticRegression':LogisticRegression(),
"RandomForestClassifier":RandomForestClassifier(),
"GradientBoostingClassifier":GradientBoostingClassifier(),
"XGBClassifier":XGBClassifier(),
"LGBMClassifier":LGBMClassifier(),
'GaussianNB':GaussianNB(),

}
# make pipline with  preprocessing 
classifier_models = {name: make_pipeline( model) for name, model in classifier_models.items()}
classifier_models["GradientBoostingClassifier"]

Pipeline(steps=[('gradientboostingclassifier', GradientBoostingClassifier())])

In [ ]:


x_train, x_val, y_train, y_val = train_test_split(X_sc, y,test_size=0.4,stratify = y,random_state=10 )
results = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [],'Time': []})
for model_name, model in classifier_models.items():
    start_time = time.time()
    model.fit(x_train, y_train)
    total_time = time.time() - start_time
    valid_pred = model.predict(x_val)
    results = results.append({"Model":    model_name,
                              "Accuracy": accuracy_score(y_val, valid_pred)*100,
                              "Bal Acc.": balanced_accuracy_score(y_val, valid_pred)*100,
                    
                              "Time":     total_time},
                              ignore_index=True)
results_ord = results.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
results_ord.index += 1 
results_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='#5fba7d')


# Best model for test data  

In [123]:
best_model=LGBMClassifier()
name='LGBMClassifier'

In [124]:
clf=Pipeline([('classification',best_model)])
test_result = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [],'Time': []})
start_time = time.time()
clf.fit(X_sc, y)
total_time = time.time() - start_time
pred = clf.predict(X_test_sc)
test_result = test_result.append({"Model":    name,
                          "Accuracy": accuracy_score(y_test, pred)*100,
                          "Bal Acc.": balanced_accuracy_score(y_test, pred)*100,
                          "Time":     total_time},
                          ignore_index=True)
test_result_ord = test_result.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
test_result_ord.index += 1 
test_result_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='#5fba7d')



ValueError: Found input variables with inconsistent numbers of samples: [5447, 5709]

In [114]:
print(classification_report(y_test, pred))
print()
print(confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

         Bus       0.00      0.00      0.00        81
         Car       0.55      0.92      0.68       224
       Still       0.87      0.90      0.88        51
       Train       0.00      0.00      0.00        72
     Walking       0.00      0.00      0.00        18

    accuracy                           0.56       446
   macro avg       0.28      0.36      0.31       446
weighted avg       0.37      0.56      0.44       446


[[  0  76   5   0   0]
 [ 10 205   2   7   0]
 [  0   5  46   0   0]
 [  0  72   0   0   0]
 [  0  18   0   0   0]]


# with optuna paramater

In [ ]:

m_=LGBMClassifier()
model_m=Pipeline([('preprocess',preprocessor),('classification',m_)])

In [ ]:
model_m.fit(X,y)

In [ ]:
pred_=model_.predict(X_test)
print(f"Accuracy {accuracy_score(y_test, pred_)*100}")
print(classification_report(y_test, pred_))
print()
print(confusion_matrix(y_test, pred_))

#  Drop some feature from target  beacuse of confusion materix result 

## Drop car  category 

In [ ]:
df_test_1   =df_test[df_test['target']!='Car']
df_train_1  =df_train[df_train['target']!='Car']

In [ ]:
print(df_test.shape)
print(df_train.shape)

# How much info reduced 

In [ ]:
print(f" After drop Car category we  reduce \n test data {100-df_test_1.shape[0]/df_test.shape[0]*100} % \n train data {100-df_train_1.shape[0]/df_train.shape[0]*100} %")

In [ ]:
print(df_train_1.shape)
print(df_test_1.shape)

In [ ]:
X_=df_train_1.drop('target',axis=1)
y_=df_train_1.target
X_test_=df_test_1.drop('target',axis=1)
y_test_=df_test_1.target

# train data 

In [ ]:
x_train_, x_val_, y_train_, y_val_ = train_test_split(X_, y_,test_size=0.4,stratify = y_,random_state=10 )
result_new = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [],'Time': []})
for model_name, model in classifier_models.items():
    start_time_ = time.time()
    model.fit(x_train_, y_train_)
    total_time_= time.time() - start_time_
    valid_pred_new = model.predict(x_val_)
    result_new = result_new.append({"Model":    model_name,
                              "Accuracy": accuracy_score(y_val_, valid_pred_new)*100,
                              "Bal Acc.": balanced_accuracy_score(y_val_, valid_pred_new)*100,
                              "Time":     total_time_},
                              ignore_index=True)
result_new_ord = result_new.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
result_new_ord.index += 1 
result_new_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='#5fba7d')

#  The highest accuracy model selected  manual tuning 

In [ ]:

best_=LGBMClassifier(boosting_type='gbdt', num_leaves=60, max_depth=6, learning_rate=0.07,
                          n_estimators=300, subsample_for_bin=200000, objective=None, class_weight=None,
                          min_split_gain=0.0, min_child_weight=0.001, min_child_samples=20, subsample=1.0, 
                          subsample_freq=0, colsample_bytree=1.0, reg_alpha=0.0, reg_lambda=0.0, 
                          random_state=None, n_jobs=- 1, silent=True, importance_type='split')
model_=Pipeline([('preprocess',preprocessor),('classification',best_)])

In [ ]:
model_.fit(X_,y_)
pred_test_1=model_.predict(X_test_)

In [ ]:
accuracy_score(y_test_, pred_test_1)*100,

In [ ]:
print(classification_report(y_test_, pred_test_1))
print()
print(confusion_matrix(y_test_, pred_test_1))

# Optuna find best parameter for selected model

In [ ]:
from sklearn.calibration import CalibratedClassifierCV
import optuna

In [ ]:
oth=Pipeline([('preprocess',preprocessor),('classification',GaussianNB())])

In [ ]:
 n_estimators = trial.suggest_int('n_estimators', 2, 20)
max_depth = int(trial.suggest_loguniform('max_depth', 1, 32))

In [ ]:
import optuna

def objective(trial):

    boosting_type = trial.suggest_categorical("boosting_type", ["gbdt", "rf"])
    max_depth = trial.suggest_int('max_depth', 1, 32)
    n_estimators = trial.suggest_int("n_estimators", 100,500)
    learning_rate=trial.suggest_float("learning_rate", 0.001,0.1)
    min_data_in_leaf= trial.suggest_int("min_data_in_leaf", 10,500)
    
    lg_lgbm = LGBMClassifier( boosting_type=boosting_type, max_depth=max_depth, 
            n_estimators=n_estimators,learning_rate=learning_rate,min_data_in_leaf=min_data_in_leaf
        )

    score = cross_val_score(lg_lgbm, X_,y_, n_jobs=-1, cv=3)
    accuracy = score.mean()
    return accuracy

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

trial = study.best_trial
print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))


# With optuna best parameter

 the best accuracy  **91.18993135011442**  in max_depth= 5, n_estimators= 300, num_leaves=70,min_data_in_leaf=60,learning_rate= 0.069

In [ ]:

lgb_af_=LGBMClassifier( max_depth= 5
, n_estimators= 300, num_leaves=70,min_data_in_leaf=60,learning_rate= 0.069)
model_end=Pipeline([('preprocess',preprocessor),('classification',lgb_af_)])

In [ ]:
model_end.fit(X_,y_)
pred_test_end=model_end.predict(X_test_)

In [ ]:
print(f"Accuracy {accuracy_score(y_test_, pred_test_end)*100}")
print(classification_report(y_test_, pred_test_end))
print()
print(confusion_matrix(y_test_, pred_test_end))

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3e7089f3-11a5-48ad-89c4-39a166311a14' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>